Get report

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -40,6 +40,11 @@ jobs:
       - name: Run Playwright tests
         run: npx playwright test tests/Ajensia/AssetManagement/AssetAssignedList.spec.js
 
+      - name: Clean previous allure-results folder
+        run: |
+          echo "Cleaning old allure-results..."
+          rm -rf allure-results || echo "❌ allure-results folder not found"
+
       - name: Check allure-results folder
         run: |
           echo "Listing files in allure-results"
@@ -48,7 +53,7 @@ jobs:
       - name: Generate Allure report
         run: |
           mkdir -p allure-report
-          echo "Generating Allure report..."
+          echo "Generating new Allure report..."
           allure generate allure-results --clean -o allure-report
           ls -la allure-report
 
